# Translations template for RadLoggerPy.
# Copyright (C) 2020 ORGANIZATION
# This file is distributed under the same license as the RadLoggerPy
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2020.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: RadLoggerPy 0.0.1.dev82\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2020-06-08 12:55+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.8.0\n"

#: radloggerpy/radloggerpy.py:47 radloggerpy/tests/test_i18n.py:45
#, python-format
msgid "Starting RadLoggerPy service on PID %s"
msgstr ""

#: radloggerpy/radloggerpy.py:67
msgid "Insufficient permissions to open device."
msgstr ""

#: radloggerpy/radloggerpy.py:70
msgid "Device does not exist"
msgstr ""

#: radloggerpy/radloggerpy.py:72
#, python-format
msgid "Device error %d"
msgstr ""

#: radloggerpy/cli/radlogger_shell.py:61
#, python-format
msgid "Initializing radloggercli %s"
msgstr ""

#: radloggerpy/cli/radlogger_shell.py:75
#, python-format
msgid "Exception raised: %s"
msgstr ""

#: radloggerpy/cli/v1/device/device_show.py:61
#: radloggerpy/cli/v1/device/device_show_serial.py:76
msgid "Multiple devices found"
msgstr ""

#: radloggerpy/cli/v1/device/device_show.py:64
#: radloggerpy/cli/v1/device/device_show_serial.py:79
msgid "Device could not be found"
msgstr ""

#: radloggerpy/common/first_time_run.py:85
msgid "Performing first time initialization"
msgstr ""

#: radloggerpy/common/first_time_run.py:97
#, python-format
msgid "Encountered error during execution of CheckTask: %s"
msgstr ""

#: radloggerpy/common/first_time_run.py:106
#, python-format
msgid "Ran task: %s"
msgstr ""

#: radloggerpy/common/first_time_run.py:108
#, python-format
msgid "Encountered error during first timeinitialization with task: %s"
msgstr ""

#: radloggerpy/common/first_time_run.py:126
#, python-format
msgid "Encountered error while performing check forfirst time init: %s"
msgstr ""

#: radloggerpy/common/first_time_run.py:151
#: radloggerpy/common/first_time_run.py:170
#, python-format
msgid "Check %s was not of type method"
msgstr ""

#: radloggerpy/common/first_time_run.py:154
#: radloggerpy/common/first_time_run.py:163
#, python-format
msgid "Task %s was not of type method"
msgstr ""

#: radloggerpy/database/database_manager.py:51
#, python-format
msgid "Failed to create session due to exception: %s"
msgstr ""

#: radloggerpy/database/database_manager.py:83
#, python-format
msgid "Checking if database: %s exists"
msgstr ""

#: radloggerpy/database/database_manager.py:86
msgid "Database file does not exist in configured path"
msgstr ""

#: radloggerpy/database/database_manager.py:105
msgid "Creating database"
msgstr ""

#: radloggerpy/database/database_manager.py:107
msgid "Creating database tables"
msgstr ""

#: radloggerpy/database/database_manager.py:110
#, python-format
msgid "Failed to create database due to error: %s"
msgstr ""

#: radloggerpy/database/objects/base.py:87
msgid "Use of deprecated ignore parameter on database object filter!"
msgstr ""

#: radloggerpy/device/device_manager.py:69
#, python-format
msgid "Configured device manager for %d workers"
msgstr ""

#: radloggerpy/models/radiationreading.py:41
msgid "RadiationReading can not have negative cpm"
msgstr ""

#: radloggerpy/tests/test_i18n.py:44
#, python-format
msgid "RadLoggerPy opstarten met PID %s"
msgstr ""

