# Dutch translations for RadLoggerPy.
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the RadLoggerPy
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2019.
#
msgid ""
msgstr ""
"Project-Id-Version: RadLoggerPy 0.0.1.dev46\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2019-11-16 10:23+0100\n"
"PO-Revision-Date: 2019-11-15 20:57+0100\n"
"Last-Translator: \n"
"Language: nl\n"
"Language-Team: \n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.7.0\n"

#: radloggerpy/radloggerpy.py:47
#, python-format
msgid "Starting RadLoggerPy service on PID %s"
msgstr "RadLoggerPy opstarten met PID %s"

#: radloggerpy/radloggerpy.py:67
msgid "Insufficient permissions to open device."
msgstr "Onvoldoende rechten om apparaat te openen."

#: radloggerpy/radloggerpy.py:70
msgid "Device does not exist"
msgstr "Apparaat bestaat niet"

#: radloggerpy/radloggerpy.py:72
#, python-format
msgid "Device error %d"
msgstr "Apparaat fout %d"

#: radloggerpy/common/first_time_run.py:85
msgid "Performing first time initialization"
msgstr "eenmalige initiatie uitvoeren"

#: radloggerpy/common/first_time_run.py:97
#, python-format
msgid "Encountered error during execution of CheckTask: %s"
msgstr "Fout ondervonden tijdens uitvoeren van CheckTask: %s"

#: radloggerpy/common/first_time_run.py:106
#, python-format
msgid "Ran task: %s"
msgstr "Taak uitgevoerd: %s"

#: radloggerpy/common/first_time_run.py:108
#, python-format
msgid "Encountered error during first timeinitialization with task: %s"
msgstr ""

#: radloggerpy/common/first_time_run.py:126
#, python-format
msgid "Encountered error while performing check forfirst time init: %s"
msgstr ""

#: radloggerpy/common/first_time_run.py:151
#: radloggerpy/common/first_time_run.py:170
#, python-format
msgid "Check %s was not of type method"
msgstr ""

#: radloggerpy/common/first_time_run.py:154
#: radloggerpy/common/first_time_run.py:163
#, python-format
msgid "Task %s was not of type method"
msgstr ""

#: radloggerpy/database/database_manager.py:44
#, python-format
msgid "Failed to create session due to exception: %s"
msgstr ""

#: radloggerpy/database/database_manager.py:76
#, python-format
msgid "Checking if database: %s exists"
msgstr ""

#: radloggerpy/database/database_manager.py:79
msgid "Database file does not exist in configured path"
msgstr ""

#: radloggerpy/database/database_manager.py:98
msgid "Creating database"
msgstr ""

#: radloggerpy/database/database_manager.py:100
msgid "Creating database tables"
msgstr ""

#: radloggerpy/database/database_manager.py:103
#, python-format
msgid "Failed to create database due to error: %s"
msgstr ""

#: radloggerpy/device/device_manager.py:69
#, python-format
msgid "Configured device manager for %d workers"
msgstr ""

#: radloggerpy/models/radiationreading.py:41
msgid "RadiationReading can not have negative cpm"
msgstr ""

#: radloggerpy/tests/test_i18n.py:30
msgid "Hello World"
msgstr ""

